### ISSUE TITLE
Specify on which split is each loss in the "Result" table (README.md)

### ISSUE THREAD

**Issue by lienz** [funcwj/conv-tasnet#6]
Hi,
Thanks for sharing your implementation. To understand the performance of your system, could you precise on which sets are computed the columns "Loss" and "SI-SDR" in the table "Result" or your README? Is it train/valid/test? For example, my guess for line 0 of the table would be train_si_sdr=17.59, valid_si_sdr = 15.45 and test_si_sdr=14.63, is it right?

**Comment by funcwj** [comment]
Yes, you are right. The 'Loss' is reported as the training and validation set on the best epoch.
