### ISSUE TITLE
The scale of the output (the predicted speech) is not consistent with the input scale (the input mixture). 

### ISSUE THREAD

**Issue by NNPanNPU** [funcwj/conv-tasnet#7]
Hi, thanks for sharing your code. I have a question in seperate.py, specifically about the code below
`
def run(args):
    mix_input = WaveReader(args.input, sample_rate=args.fs)
    computer = NnetComputer(args.checkpoint, args.gpu)
    for key, mix_samps in mix_input:
        logger.info("Compute on utterance {}...".format(key))
        spks = computer.compute(mix_samps)
        norm = np.linalg.norm(mix_samps, np.inf)
        for idx, samps in enumerate(spks):
           samps = samps[:mix_samps.size]
           samps = samps * norm / np.max(np.abs(samps))
           write_wav(
                os.path.join(args.dump_dir, "spk{}/{}.wav".format(
                idx + 1, key)),
                samps,
                fs=args.fs)
`
           
I found the separated speeches are not in the same energy level as that of the mixture, though the performance is really great. I debug the code and surprisingly found that  max(mix_samps) is around 1, while max(samps) is around 200 before doing norm. 

I don't think we should do norm here, since this changes the separated speech energy level. 
` samps = samps * norm / np.max(np.abs(samps))` 
However, without normalization, as I said, max(samps) is around 200. Do you know why? And how to solve this?

**Comment by funcwj** [comment]
It can not be solved well. Here are some reasons: 

1) The learned 1d convolutional transform weights are not guaranted to be orthogonal and reconstruct signals perfectly, which is not consistant with the STFTs.
2) The loss function (Si-SNR) is scale invariant, which means the loss is insensitve to the scale of the signals (the energy).

I did the normalization on the input signals, which forces the value of each sample locating between -1 and 1. You can did it as well for the estimated signals.
Another thing is that the energy has no impact on the quality of the signals and it's not important in most instances.

**Comment by NNPanNPU** [comment]
Thanks for getting back. Yeah, the system works great and this does not affect speech quality. However, this is a very import issue for communication systems which demand real-time processing. When the speaker changes his/her volume during talking, this will be an issue.  

Thanks again. I appreciate the discussion.
